passionproject/Models/Beer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;



//Code referenced from Christine Bittle and 
//https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application
namespace passionproject.Models
{
    public class Beer
    {
        [Key]
        public int BeerID { get; set; }

        [Required, StringLength(255), Display(Name = "Beer Name")]
        public string BeerName { get; set; }

        [Required, StringLength(int.MaxValue), Display(Name = "Beer Description")]
        public string BeerDescription { get; set; }

        public virtual ICollection<Review> Review { get; set; }
    }
}

passionproject/Controllers/BeerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using passionproject.Models;
using passionproject.Models.ViewModels;
using System.Data.Entity;
using System.Net;
using System.Diagnostics;

namespace passionproject.Controllers
{
    public class BeerController : Controller
    {
        private BeerCMSContext db = new BeerCMSContext();
        // GET: Beer
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        //main list of beer with links
        public ActionResult List()
        {
            IEnumerable<Beer> beer = db.Beers.ToList();
            return View(beer);
        }
        public ActionResult New()
        {
            return View();
        }
        //when create new is clicked
        [HttpPost]
        public ActionResult Create(string BeerName_New, string BeerDescription_New)
        {
            string DBquery = "insert into Beers (BeerName, BeerDescription) values (@name, @description)";
            SqlParameter[] createparams = new SqlParameter[2];
            createparams[0] = new SqlParameter("@Name", BeerName_New);
            createparams[1] = new SqlParameter("@Description", BeerDescription_New);

            db.Database.ExecuteSqlCommand(DBquery, createparams);
            return RedirectToAction("List");
        }
        //when edit is clicked
        [HttpPost]
        public ActionResult Edit(int id, string BeerName, string BeerDescription)
        {
            string DBquery = "update Beers set BeerName=@Name, BeerDescription=@Description where BeerID=@id";
            SqlParameter[] editparams = new SqlParameter[3];
            editparams[0] = new SqlParameter("@Name", BeerName);
            editparams[1] = new SqlParameter("@Description", BeerDescription);
            editparams[2] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(DBquery, editparams);

            return RedirectToAction("Details/" + id);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }
        //when details is clicked
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if ( beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }
        public ActionResult Show(int? id)
        {
            if ((id == null) || (db.Beers.Find(id) == null))
            {
                return HttpNotFound();
            }
            string DBquery = "select * from beers where beerid=@id";
            SqlParameter[] showparams = new SqlParameter[1];
            showparams[0] = new SqlParameter("@id", id);

            Beer allbeer = db.Beers.SqlQuery(DBquery, showparams).FirstOrDefault();

            return View(allbeer);
        }
        //when delete is clicked
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Beer beer = db.Beers.Find(id);
            db.Beers.Remove(beer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

passionproject/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using passionproject.Models;
using System.Diagnostics;
using passionproject.Models.ViewModels;


namespace passionproject.Controllers
{
    public class ReviewController : Controller
    {
        private BeerCMSContext db = new BeerCMSContext();
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        public ActionResult List()
        {
            return View(db.Reviews.ToList());
        }
        public ActionResult New()
        {
            return View(db.Beers.ToList());
        }
        [HttpPost]
        public ActionResult Create(int? id, string ReviewTitle_New, string ReviewerName_New, string ReviewContent_New, int? ReviewBeer_New)
        {
            string DBquery = "insert into Reviews (ReviewTitle, ReviewerName, ReviewContent, beer_BeerID)" +
            "values (@Title,@Name,@Content,@bid)";

            SqlParameter[] reviewparams = new SqlParameter[4];
            reviewparams[0] = new SqlParameter("@Title", ReviewTitle_New);
            reviewparams[1] = new SqlParameter("@Name", ReviewerName_New);
            reviewparams[2] = new SqlParameter("@Content", ReviewContent_New);
            reviewparams[3] = new SqlParameter("@bid", ReviewBeer_New);

            db.Database.ExecuteSqlCommand(DBquery, reviewparams);
            Debug.WriteLine(DBquery);

            return RedirectToAction("Details/"+ReviewBeer_New, "Beer");
        }
        [HttpPost]
        public ActionResult Edit(int? id, string ReviewTitle, string ReviewerName, string ReviewContent, int? ReviewBeer)
        {
            string DBquery = "update Reviews set ReviewTitle=@Title, ReviewerName=@Name, ReviewContent=@Content where ReviewID=@id";
            SqlParameter[] reviewparams = new SqlParameter[4];
            reviewparams[0] = new SqlParameter("@Title", ReviewTitle);
            reviewparams[1] = new SqlParameter("@Name", ReviewerName);
            reviewparams[2] = new SqlParameter("@Content", ReviewContent);
            reviewparams[3] = new SqlParameter("@bid", ReviewBeer);


            db.Database.ExecuteSqlCommand(DBquery, reviewparams);

            return RedirectToAction("List/");
        }
        public ActionResult Delete(int? id)
        {
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("List", "Beer");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }   
    }
}

passionproject/Views/Beer/Delete.cshtml
@model passionproject.Models.Beer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this beer?</h3>
<div>
    <h4>Beer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BeerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BeerDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BeerDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

passionproject/Views/Beer/Details.cshtml
@model passionproject.Models.Beer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BeerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<h2>@Model.BeerName</h2>
<hr />
<p>@Model.BeerDescription</p>
<br />
<br />
<h3 id="userReviewHeading">User Reviews</h3>
@Html.ActionLink("Submit Review", "New/", "Review")
<div>
    @foreach (var review in Model.Review)
    {
    <div>
        <hr />
        <h4 id="reviewHeader">@Html.DisplayFor(item => review.ReviewTitle)</h4>
        <p id="reviewAuthor">@Html.DisplayFor(item => review.ReviewerName)</p>
        <p id="reviewBody">@Html.DisplayFor(item => review.ReviewContent)</p>
        <p>
            @Html.ActionLink("Edit", "Edit/" + review.ReviewID, "Review")
            @Html.ActionLink("Delete", "Delete/" + review.ReviewID, "Review")
        </p>
    </div>
    }
</div>

passionproject/Views/Beer/Edit.cshtml
@model passionproject.Models.Beer


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Beer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BeerID)

        <div class="form-group">
            @Html.LabelFor(model => model.BeerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeerDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BeerDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BeerDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

passionproject/Views/Beer/List.cshtml
@model IEnumerable<passionproject.Models.Beer>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "New")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BeerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BeerDescription)
        </th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>

            <a href="@Url.Action("Details/" + item.BeerID)">@Html.DisplayFor(modelItem => item.BeerName)</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeerDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BeerID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BeerID })
        </td>
    </tr>
}
</table>

passionproject/Views/Beer/New.cshtml
@model passionproject.Models.ViewModels.ReviewEdit
@{
    ViewBag.Title = "New";
}

<h2>Add Beer</h2>
<form method="POST" action="/Beer/Create">
    <div class="inprow">
        <label class="inplabel">Name</label>
        <input id="BeerName_New" name="BeerName_New" />
    </div>
    <br />
    <div class="inprow">
        <label class="inplabel">Description</label>
        <textarea id="BeerDescription_New" name="BeerDescription_New"></textarea>
    </div>
    <br />
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>